### PR TITLE
[MIRROR] modernized datum ais & jps pathfinding

### PR DESCRIPTION
**Pull request by SinguloBot**
Original PR: https://github.com/BeeStation/BeeStation-Hornet/pull/5422
--------------------

## About The Pull Request

tgstation/tgstation#56780
tgstation/tgstation#57186
tgstation/tgstation#58631

## Why It's Good For The Game

simply a less costly system than Astar, who doesn't want to play fetch with ian anyways

## Changelog
:cl: Ryll-Ryll, jupyterkat, ninjanomnom
add: Dogs now have all-new AI! Go throw a grenade at Ian and see what happens!
add: Added AI datum support for complex JPS pathing
refactor: Implements JPS Pathfinding
fix: janky monkey ais
fix: Monkeys are once again capable of using guns, take back your freedom!
add: Monkey ai is now actually able to make use of guns instead of just player controlled monkeys.
add: Monkey ai will prioritize guns once they learn of what guns can do.
add: Monkey ai now understands the ancient art of throwing.
add: Monkey ai will use random objects on each other in their surroundings and in their hands.
add: Monkey ai will occasionally "gift" people things.
add: Monkey ai consumes food once in a while according to their desire.
/:cl:

### CODE REVIEW

**Comment by Urumasi** [comment]
Holy shit datum AI

**Comment by Urumasi** [comment]
remirror

**Comment by KubeRoot** [comment]
remirror

**Comment by KubeRoot** [comment]
Depends on https://github.com/SinguloStation13/SinguloStation-Red/pull/344

**Comment by KubeRoot** [comment]
I think you resolved the conflict the wrong way around and implemented https://github.com/SinguloStation13/SinguloStation-Red/pull/344, not entirely sure.

**Comment by Laboredih123** [comment]
Yes

**Comment by Laboredih123** [comment]
Without the define it was a failed compile

**Comment by Laboredih123** [comment]
Anyway I believe I can merge?

**Comment by KubeRoot** [comment]
> Without the define it was a failed compile

It was a failed compile because you resolved the conflict incorrectly - the conflict was because we didn't have https://github.com/SinguloStation13/SinguloStation-Red/pull/344, which was where the added code was coming from - however, adding that code is fine, since it might be useful in the future, and further upstream PRs might rely on it existing.

**Comment by Laboredih123** [comment]
So can I merge?

**Comment by Laboredih123** [comment]
I'm guessing yes

**Pull request merged**
