### PR TITLE
[MIRROR] Removes hungover spawn landmarks, refactors random safe turf a bit

### PR DESCRIPTION
**Pull request by SinguloBot**
Original PR: https://github.com/BeeStation/BeeStation-Hornet/pull/5498
--------------------

## About The Pull Request

Also minor pubby change - I fixed some line near departures.

Hungover now places its spawns randomly instead of bloating map files.

Also [issue link stripped]

## Why It's Good For The Game

Requested and fix bug

## Changelog
:cl:
del: Removed hangover landmarks
tweak: Hangover now dynamically places its spawns around the station
fix: Fixed random_safe_station_turf sometimes returning null even if it had viable turf
/:cl:

### CODE REVIEW

**Comment by Urumasi** [comment]
Looks good, but has map merge conflicts

**Comment by KubeRoot** [comment]
Likely depends on https://github.com/SinguloStation13/SinguloStation-Red/pull/341

**Comment by KubeRoot** [comment]
remirror

**Review by Laboredih123 — APPROVED** [review]
Seems good, uru please merge, other PRs rely on this

**Pull request merged**
