### PR TITLE
[MIRROR] arts & canvases update

### PR DESCRIPTION
**Pull request by SinguloBot**
Original PR: https://github.com/BeeStation/BeeStation-Hornet/pull/5431
--------------------

## About The Pull Request

tgstation/tgstation#48834
tgstation/tgstation#53585
tgstation/tgstation#56349
tgstation/tgstation#53994
tgstation/tgstation#59146
and multiple supporting loose commits

reeeeee

## Why It's Good For The Game

artss

## Changelog
:cl: tralezab, AnturK
add: curators can now print paintings
add: persistent paintings
add: AIs can now pick paintings as their screens
add: tgui canvases
/:cl:

### CODE REVIEW

**Comment by Laboredih123** [comment]
remirror

**Review by Laboredih123 — APPROVED** [review]
I tested the PR in a dev server, code seems fine too.

**Review by KubeRoot — APPROVED** [review]
The tgui interface apparently breaks without persistence, and in general it seems in need of some cleanup, but everything seems to be in order.

**Comment by Laboredih123** [comment]
Terra hasn't testmerged it it seems so Imma just yeet it into the repo.

**Pull request merged**
