### PR TITLE
[MIRROR] Dockerfile updates + BYOND version bump

### PR DESCRIPTION
**Pull request by Terra1**
Original PR: https://github.com/BeeStation/BeeStation-Hornet/pull/5063
--------------------

## About The Pull Request

Rewrites most of the Dockerfile so that it adheres to modern standards and properly utilizes our several dependency changes. These changes will unfortunately result in a final image size that's about 66 MB larger than our previous images. 278 MB up from 212 MB (at the time of writing).

Our byond hub image has also been updated to use a Debian base over the previous 32-bit Ubuntu image. https://github.com/BeeStation/byond-docker/commit/116121a8ad37e792e9046b90baf34d63e0841d04

## Changelog
N/A

### CODE REVIEW

**Comment by KubeRoot** [comment]
domirror 4861

**Comment by KubeRoot** [comment]
domirror 4861

**Comment by KubeRoot** [comment]
Will need to be remirrored after https://github.com/SinguloStation13/SinguloStation-Red/pull/120 is merged

**Comment by KubeRoot** [comment]
remirror, let's try this for real

**Review by Urumasi — APPROVED** [review]

**Comment by KubeRoot** [comment]
It's not like we even use docker so I don't even know how to test this, gonna merge and worry later if something breaks.

**Pull request merged**
